###ユーザー情報取得
GET http://localhost:8000/api/users/2
Accept: application/json

###ユーザー一覧取得
GET http://localhost:8000/api/users?min_level=5&max_level=8
Accept: application/json

###ユーザー一覧取得(サーバー)
GET http://48.218.28.94/api/users?min_level=5&max_level=8
Accept: application/json

###ユーザーゲームログイン
GET http://localhost:8000/api/login/1
Accept: application/json

###アイテム一覧取得
GET http://48.218.28.94/api/itemList
Accept: application/json

###ステージ一覧取得
GET https://api-gravityturning.japaneast.cloudapp.azure.com/api/stageList
Accept: application/json

###指定ユーザー所持アイテム情報取得
GET https://api-gravityturning.japaneast.cloudapp.azure.com/api/userItems/1
Accept: application/json

###マスターメール一覧取得
GET https://api-gravityturning.japaneast.cloudapp.azure.com/api/mailList
Accept: application/json

###指定ユーザー所持メール情報取得
GET http://48.218.28.94/api/userMails/1
Accept: application/json

###指定ユーザーフォロー情報取得
GET http://48.218.28.94/api/userFollows/1
Accept: application/json

###ユーザー登録
POST https://api-gravityturning.japaneast.cloudapp.azure.com/api/users/store
Content-Type: application/json
Accept: application/json

{
    "name": "8355557d-6cb0-4ed9-932e-b7b94a7b42de",
    "password": "f1aff659-e327-4711-8894-cae2f26b5b3f"
}

###ユーザー更新
POST http://48.218.28.94/users/update
Content-Type: application/json
Accept: application/json

{
    "user_id": 2,
    "user_name": "SyuEn1"
}

###ユーザー削除
GET http://localhost:8000/api/users/destroy
Content-Type: application/json
Accept: application/json

{
    "user_id": 4
}

###ユーザー所持アイテム情報更新
POST http://localhost:8000/api/users/posItemUpdate
Content-Type: application/json
Accept: application/json

{
    "user_id": 20,
    "change_item_id": 3,
    "change_item_num": 10
}

###ユーザーフォロー情報追加
POST http://localhost:8000/api/users/follow
Content-Type: application/json
Accept: application/json

{
    "follow_user_id": 3,
    "follower_user_id": 52
}

###ユーザーフォロー情報削除
POST http://localhost:8000/api/users/unfollow
Content-Type: application/json
Accept: application/json

{
    "unfollow_user_id": 3,
    "follower_user_id": 52
}

###ユーザーメール開封更新
POST http://localhost:8000/api/users/mailUpdate
Content-Type: application/json
Accept: application/json

{
    "user_id": 2,
    "mail_id": 1
}

###https://api-gravityturning.japaneast.cloudapp.azure.com/api
###スコアランキング一覧取得
GET https://api-gravityturning.japaneast.cloudapp.azure.com/api/scoreRanking
Accept: application/json


###スコアランキング取得(特定ユーザー)
GET https://api-gravityturning.japaneast.cloudapp.azure.com/api/users/getRank
Content-Type: application/json
Accept: application/json

{
    "user_id": 99
}

###スコアランキング取得(自分のランキング)
GET https://api-gravityturning.japaneast.cloudapp.azure.com/api/users/getMyScoreRank
Content-Type: application/json
Accept: application/json

{
    "user_id": 99
}


###スコアランキング登録
POST https://api-gravityturning.japaneast.cloudapp.azure.com/api/users/sendScore
Content-Type: application/json
Accept: application/json

{
    "user_id": 99,
    "user_name": "99本アニメ",
    "score": 100000
}
